image: gitpod/workspace-full:branch-pr-392
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true
